name: Terraform Linting

on:
  pull_request:
    branches: [test]
  
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 1.0.9
      - name: Terraform fmt
        run: terraform fmt -check
      - name: Terraform validate
        run: terraform validate
